// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DS_Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DS_5fProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DS_5fProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DS_5fProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DS_5fProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DS_5fProtocol_2eproto;
namespace DS_Protobuf {
class DSGameinfo;
struct DSGameinfoDefaultTypeInternal;
extern DSGameinfoDefaultTypeInternal _DSGameinfo_default_instance_;
class DSPlayerinfo;
struct DSPlayerinfoDefaultTypeInternal;
extern DSPlayerinfoDefaultTypeInternal _DSPlayerinfo_default_instance_;
class NewDSGame_Request;
struct NewDSGame_RequestDefaultTypeInternal;
extern NewDSGame_RequestDefaultTypeInternal _NewDSGame_Request_default_instance_;
class NewDSGame_Response;
struct NewDSGame_ResponseDefaultTypeInternal;
extern NewDSGame_ResponseDefaultTypeInternal _NewDSGame_Response_default_instance_;
}  // namespace DS_Protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::DS_Protobuf::DSGameinfo* Arena::CreateMaybeMessage<::DS_Protobuf::DSGameinfo>(Arena*);
template<> ::DS_Protobuf::DSPlayerinfo* Arena::CreateMaybeMessage<::DS_Protobuf::DSPlayerinfo>(Arena*);
template<> ::DS_Protobuf::NewDSGame_Request* Arena::CreateMaybeMessage<::DS_Protobuf::NewDSGame_Request>(Arena*);
template<> ::DS_Protobuf::NewDSGame_Response* Arena::CreateMaybeMessage<::DS_Protobuf::NewDSGame_Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace DS_Protobuf {

// ===================================================================

class DSPlayerinfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DS_Protobuf.DSPlayerinfo) */ {
 public:
  inline DSPlayerinfo() : DSPlayerinfo(nullptr) {}
  ~DSPlayerinfo() override;
  explicit PROTOBUF_CONSTEXPR DSPlayerinfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DSPlayerinfo(const DSPlayerinfo& from);
  DSPlayerinfo(DSPlayerinfo&& from) noexcept
    : DSPlayerinfo() {
    *this = ::std::move(from);
  }

  inline DSPlayerinfo& operator=(const DSPlayerinfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline DSPlayerinfo& operator=(DSPlayerinfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DSPlayerinfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const DSPlayerinfo* internal_default_instance() {
    return reinterpret_cast<const DSPlayerinfo*>(
               &_DSPlayerinfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DSPlayerinfo& a, DSPlayerinfo& b) {
    a.Swap(&b);
  }
  inline void Swap(DSPlayerinfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DSPlayerinfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DSPlayerinfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DSPlayerinfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DSPlayerinfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DSPlayerinfo& from) {
    DSPlayerinfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DSPlayerinfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DS_Protobuf.DSPlayerinfo";
  }
  protected:
  explicit DSPlayerinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersnameFieldNumber = 2,
    kTokenFieldNumber = 3,
    kIdFieldNumber = 1,
    kGroupFieldNumber = 4,
  };
  // string playersname = 2;
  void clear_playersname();
  const std::string& playersname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_playersname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_playersname();
  PROTOBUF_NODISCARD std::string* release_playersname();
  void set_allocated_playersname(std::string* playersname);
  private:
  const std::string& _internal_playersname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_playersname(const std::string& value);
  std::string* _internal_mutable_playersname();
  public:

  // string token = 3;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 group = 4;
  void clear_group();
  int32_t group() const;
  void set_group(int32_t value);
  private:
  int32_t _internal_group() const;
  void _internal_set_group(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:DS_Protobuf.DSPlayerinfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr playersname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    int32_t id_;
    int32_t group_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DS_5fProtocol_2eproto;
};
// -------------------------------------------------------------------

class DSGameinfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DS_Protobuf.DSGameinfo) */ {
 public:
  inline DSGameinfo() : DSGameinfo(nullptr) {}
  ~DSGameinfo() override;
  explicit PROTOBUF_CONSTEXPR DSGameinfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DSGameinfo(const DSGameinfo& from);
  DSGameinfo(DSGameinfo&& from) noexcept
    : DSGameinfo() {
    *this = ::std::move(from);
  }

  inline DSGameinfo& operator=(const DSGameinfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline DSGameinfo& operator=(DSGameinfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DSGameinfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const DSGameinfo* internal_default_instance() {
    return reinterpret_cast<const DSGameinfo*>(
               &_DSGameinfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DSGameinfo& a, DSGameinfo& b) {
    a.Swap(&b);
  }
  inline void Swap(DSGameinfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DSGameinfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DSGameinfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DSGameinfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DSGameinfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DSGameinfo& from) {
    DSGameinfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DSGameinfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DS_Protobuf.DSGameinfo";
  }
  protected:
  explicit DSGameinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersinfoFieldNumber = 5,
    kPlayersnumFieldNumber = 1,
    kPlayerslimitFieldNumber = 2,
    kMapidFieldNumber = 3,
    kHostidFieldNumber = 4,
  };
  // repeated .DS_Protobuf.DSPlayerinfo playersinfo = 5;
  int playersinfo_size() const;
  private:
  int _internal_playersinfo_size() const;
  public:
  void clear_playersinfo();
  ::DS_Protobuf::DSPlayerinfo* mutable_playersinfo(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DS_Protobuf::DSPlayerinfo >*
      mutable_playersinfo();
  private:
  const ::DS_Protobuf::DSPlayerinfo& _internal_playersinfo(int index) const;
  ::DS_Protobuf::DSPlayerinfo* _internal_add_playersinfo();
  public:
  const ::DS_Protobuf::DSPlayerinfo& playersinfo(int index) const;
  ::DS_Protobuf::DSPlayerinfo* add_playersinfo();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DS_Protobuf::DSPlayerinfo >&
      playersinfo() const;

  // int32 playersnum = 1;
  void clear_playersnum();
  int32_t playersnum() const;
  void set_playersnum(int32_t value);
  private:
  int32_t _internal_playersnum() const;
  void _internal_set_playersnum(int32_t value);
  public:

  // int32 playerslimit = 2;
  void clear_playerslimit();
  int32_t playerslimit() const;
  void set_playerslimit(int32_t value);
  private:
  int32_t _internal_playerslimit() const;
  void _internal_set_playerslimit(int32_t value);
  public:

  // int32 mapid = 3;
  void clear_mapid();
  int32_t mapid() const;
  void set_mapid(int32_t value);
  private:
  int32_t _internal_mapid() const;
  void _internal_set_mapid(int32_t value);
  public:

  // int32 hostid = 4;
  void clear_hostid();
  int32_t hostid() const;
  void set_hostid(int32_t value);
  private:
  int32_t _internal_hostid() const;
  void _internal_set_hostid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:DS_Protobuf.DSGameinfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DS_Protobuf::DSPlayerinfo > playersinfo_;
    int32_t playersnum_;
    int32_t playerslimit_;
    int32_t mapid_;
    int32_t hostid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DS_5fProtocol_2eproto;
};
// -------------------------------------------------------------------

class NewDSGame_Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DS_Protobuf.NewDSGame_Request) */ {
 public:
  inline NewDSGame_Request() : NewDSGame_Request(nullptr) {}
  ~NewDSGame_Request() override;
  explicit PROTOBUF_CONSTEXPR NewDSGame_Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NewDSGame_Request(const NewDSGame_Request& from);
  NewDSGame_Request(NewDSGame_Request&& from) noexcept
    : NewDSGame_Request() {
    *this = ::std::move(from);
  }

  inline NewDSGame_Request& operator=(const NewDSGame_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewDSGame_Request& operator=(NewDSGame_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewDSGame_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const NewDSGame_Request* internal_default_instance() {
    return reinterpret_cast<const NewDSGame_Request*>(
               &_NewDSGame_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NewDSGame_Request& a, NewDSGame_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(NewDSGame_Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewDSGame_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewDSGame_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NewDSGame_Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NewDSGame_Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NewDSGame_Request& from) {
    NewDSGame_Request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewDSGame_Request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DS_Protobuf.NewDSGame_Request";
  }
  protected:
  explicit NewDSGame_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGameinfoFieldNumber = 1,
  };
  // .DS_Protobuf.DSGameinfo gameinfo = 1;
  bool has_gameinfo() const;
  private:
  bool _internal_has_gameinfo() const;
  public:
  void clear_gameinfo();
  const ::DS_Protobuf::DSGameinfo& gameinfo() const;
  PROTOBUF_NODISCARD ::DS_Protobuf::DSGameinfo* release_gameinfo();
  ::DS_Protobuf::DSGameinfo* mutable_gameinfo();
  void set_allocated_gameinfo(::DS_Protobuf::DSGameinfo* gameinfo);
  private:
  const ::DS_Protobuf::DSGameinfo& _internal_gameinfo() const;
  ::DS_Protobuf::DSGameinfo* _internal_mutable_gameinfo();
  public:
  void unsafe_arena_set_allocated_gameinfo(
      ::DS_Protobuf::DSGameinfo* gameinfo);
  ::DS_Protobuf::DSGameinfo* unsafe_arena_release_gameinfo();

  // @@protoc_insertion_point(class_scope:DS_Protobuf.NewDSGame_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::DS_Protobuf::DSGameinfo* gameinfo_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DS_5fProtocol_2eproto;
};
// -------------------------------------------------------------------

class NewDSGame_Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DS_Protobuf.NewDSGame_Response) */ {
 public:
  inline NewDSGame_Response() : NewDSGame_Response(nullptr) {}
  ~NewDSGame_Response() override;
  explicit PROTOBUF_CONSTEXPR NewDSGame_Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NewDSGame_Response(const NewDSGame_Response& from);
  NewDSGame_Response(NewDSGame_Response&& from) noexcept
    : NewDSGame_Response() {
    *this = ::std::move(from);
  }

  inline NewDSGame_Response& operator=(const NewDSGame_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewDSGame_Response& operator=(NewDSGame_Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewDSGame_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const NewDSGame_Response* internal_default_instance() {
    return reinterpret_cast<const NewDSGame_Response*>(
               &_NewDSGame_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(NewDSGame_Response& a, NewDSGame_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(NewDSGame_Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewDSGame_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewDSGame_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NewDSGame_Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NewDSGame_Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NewDSGame_Response& from) {
    NewDSGame_Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewDSGame_Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DS_Protobuf.NewDSGame_Response";
  }
  protected:
  explicit NewDSGame_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // int32 Port = 2;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:DS_Protobuf.NewDSGame_Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t result_;
    int32_t port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DS_5fProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DSPlayerinfo

// int32 id = 1;
inline void DSPlayerinfo::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t DSPlayerinfo::_internal_id() const {
  return _impl_.id_;
}
inline int32_t DSPlayerinfo::id() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSPlayerinfo.id)
  return _internal_id();
}
inline void DSPlayerinfo::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void DSPlayerinfo::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSPlayerinfo.id)
}

// string playersname = 2;
inline void DSPlayerinfo::clear_playersname() {
  _impl_.playersname_.ClearToEmpty();
}
inline const std::string& DSPlayerinfo::playersname() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSPlayerinfo.playersname)
  return _internal_playersname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DSPlayerinfo::set_playersname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.playersname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSPlayerinfo.playersname)
}
inline std::string* DSPlayerinfo::mutable_playersname() {
  std::string* _s = _internal_mutable_playersname();
  // @@protoc_insertion_point(field_mutable:DS_Protobuf.DSPlayerinfo.playersname)
  return _s;
}
inline const std::string& DSPlayerinfo::_internal_playersname() const {
  return _impl_.playersname_.Get();
}
inline void DSPlayerinfo::_internal_set_playersname(const std::string& value) {
  
  _impl_.playersname_.Set(value, GetArenaForAllocation());
}
inline std::string* DSPlayerinfo::_internal_mutable_playersname() {
  
  return _impl_.playersname_.Mutable(GetArenaForAllocation());
}
inline std::string* DSPlayerinfo::release_playersname() {
  // @@protoc_insertion_point(field_release:DS_Protobuf.DSPlayerinfo.playersname)
  return _impl_.playersname_.Release();
}
inline void DSPlayerinfo::set_allocated_playersname(std::string* playersname) {
  if (playersname != nullptr) {
    
  } else {
    
  }
  _impl_.playersname_.SetAllocated(playersname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.playersname_.IsDefault()) {
    _impl_.playersname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DS_Protobuf.DSPlayerinfo.playersname)
}

// string token = 3;
inline void DSPlayerinfo::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& DSPlayerinfo::token() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSPlayerinfo.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DSPlayerinfo::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSPlayerinfo.token)
}
inline std::string* DSPlayerinfo::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:DS_Protobuf.DSPlayerinfo.token)
  return _s;
}
inline const std::string& DSPlayerinfo::_internal_token() const {
  return _impl_.token_.Get();
}
inline void DSPlayerinfo::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* DSPlayerinfo::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* DSPlayerinfo::release_token() {
  // @@protoc_insertion_point(field_release:DS_Protobuf.DSPlayerinfo.token)
  return _impl_.token_.Release();
}
inline void DSPlayerinfo::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DS_Protobuf.DSPlayerinfo.token)
}

// int32 group = 4;
inline void DSPlayerinfo::clear_group() {
  _impl_.group_ = 0;
}
inline int32_t DSPlayerinfo::_internal_group() const {
  return _impl_.group_;
}
inline int32_t DSPlayerinfo::group() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSPlayerinfo.group)
  return _internal_group();
}
inline void DSPlayerinfo::_internal_set_group(int32_t value) {
  
  _impl_.group_ = value;
}
inline void DSPlayerinfo::set_group(int32_t value) {
  _internal_set_group(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSPlayerinfo.group)
}

// -------------------------------------------------------------------

// DSGameinfo

// int32 playersnum = 1;
inline void DSGameinfo::clear_playersnum() {
  _impl_.playersnum_ = 0;
}
inline int32_t DSGameinfo::_internal_playersnum() const {
  return _impl_.playersnum_;
}
inline int32_t DSGameinfo::playersnum() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSGameinfo.playersnum)
  return _internal_playersnum();
}
inline void DSGameinfo::_internal_set_playersnum(int32_t value) {
  
  _impl_.playersnum_ = value;
}
inline void DSGameinfo::set_playersnum(int32_t value) {
  _internal_set_playersnum(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSGameinfo.playersnum)
}

// int32 playerslimit = 2;
inline void DSGameinfo::clear_playerslimit() {
  _impl_.playerslimit_ = 0;
}
inline int32_t DSGameinfo::_internal_playerslimit() const {
  return _impl_.playerslimit_;
}
inline int32_t DSGameinfo::playerslimit() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSGameinfo.playerslimit)
  return _internal_playerslimit();
}
inline void DSGameinfo::_internal_set_playerslimit(int32_t value) {
  
  _impl_.playerslimit_ = value;
}
inline void DSGameinfo::set_playerslimit(int32_t value) {
  _internal_set_playerslimit(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSGameinfo.playerslimit)
}

// int32 mapid = 3;
inline void DSGameinfo::clear_mapid() {
  _impl_.mapid_ = 0;
}
inline int32_t DSGameinfo::_internal_mapid() const {
  return _impl_.mapid_;
}
inline int32_t DSGameinfo::mapid() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSGameinfo.mapid)
  return _internal_mapid();
}
inline void DSGameinfo::_internal_set_mapid(int32_t value) {
  
  _impl_.mapid_ = value;
}
inline void DSGameinfo::set_mapid(int32_t value) {
  _internal_set_mapid(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSGameinfo.mapid)
}

// int32 hostid = 4;
inline void DSGameinfo::clear_hostid() {
  _impl_.hostid_ = 0;
}
inline int32_t DSGameinfo::_internal_hostid() const {
  return _impl_.hostid_;
}
inline int32_t DSGameinfo::hostid() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSGameinfo.hostid)
  return _internal_hostid();
}
inline void DSGameinfo::_internal_set_hostid(int32_t value) {
  
  _impl_.hostid_ = value;
}
inline void DSGameinfo::set_hostid(int32_t value) {
  _internal_set_hostid(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.DSGameinfo.hostid)
}

// repeated .DS_Protobuf.DSPlayerinfo playersinfo = 5;
inline int DSGameinfo::_internal_playersinfo_size() const {
  return _impl_.playersinfo_.size();
}
inline int DSGameinfo::playersinfo_size() const {
  return _internal_playersinfo_size();
}
inline void DSGameinfo::clear_playersinfo() {
  _impl_.playersinfo_.Clear();
}
inline ::DS_Protobuf::DSPlayerinfo* DSGameinfo::mutable_playersinfo(int index) {
  // @@protoc_insertion_point(field_mutable:DS_Protobuf.DSGameinfo.playersinfo)
  return _impl_.playersinfo_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DS_Protobuf::DSPlayerinfo >*
DSGameinfo::mutable_playersinfo() {
  // @@protoc_insertion_point(field_mutable_list:DS_Protobuf.DSGameinfo.playersinfo)
  return &_impl_.playersinfo_;
}
inline const ::DS_Protobuf::DSPlayerinfo& DSGameinfo::_internal_playersinfo(int index) const {
  return _impl_.playersinfo_.Get(index);
}
inline const ::DS_Protobuf::DSPlayerinfo& DSGameinfo::playersinfo(int index) const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.DSGameinfo.playersinfo)
  return _internal_playersinfo(index);
}
inline ::DS_Protobuf::DSPlayerinfo* DSGameinfo::_internal_add_playersinfo() {
  return _impl_.playersinfo_.Add();
}
inline ::DS_Protobuf::DSPlayerinfo* DSGameinfo::add_playersinfo() {
  ::DS_Protobuf::DSPlayerinfo* _add = _internal_add_playersinfo();
  // @@protoc_insertion_point(field_add:DS_Protobuf.DSGameinfo.playersinfo)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DS_Protobuf::DSPlayerinfo >&
DSGameinfo::playersinfo() const {
  // @@protoc_insertion_point(field_list:DS_Protobuf.DSGameinfo.playersinfo)
  return _impl_.playersinfo_;
}

// -------------------------------------------------------------------

// NewDSGame_Request

// .DS_Protobuf.DSGameinfo gameinfo = 1;
inline bool NewDSGame_Request::_internal_has_gameinfo() const {
  return this != internal_default_instance() && _impl_.gameinfo_ != nullptr;
}
inline bool NewDSGame_Request::has_gameinfo() const {
  return _internal_has_gameinfo();
}
inline void NewDSGame_Request::clear_gameinfo() {
  if (GetArenaForAllocation() == nullptr && _impl_.gameinfo_ != nullptr) {
    delete _impl_.gameinfo_;
  }
  _impl_.gameinfo_ = nullptr;
}
inline const ::DS_Protobuf::DSGameinfo& NewDSGame_Request::_internal_gameinfo() const {
  const ::DS_Protobuf::DSGameinfo* p = _impl_.gameinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::DS_Protobuf::DSGameinfo&>(
      ::DS_Protobuf::_DSGameinfo_default_instance_);
}
inline const ::DS_Protobuf::DSGameinfo& NewDSGame_Request::gameinfo() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.NewDSGame_Request.gameinfo)
  return _internal_gameinfo();
}
inline void NewDSGame_Request::unsafe_arena_set_allocated_gameinfo(
    ::DS_Protobuf::DSGameinfo* gameinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.gameinfo_);
  }
  _impl_.gameinfo_ = gameinfo;
  if (gameinfo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DS_Protobuf.NewDSGame_Request.gameinfo)
}
inline ::DS_Protobuf::DSGameinfo* NewDSGame_Request::release_gameinfo() {
  
  ::DS_Protobuf::DSGameinfo* temp = _impl_.gameinfo_;
  _impl_.gameinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DS_Protobuf::DSGameinfo* NewDSGame_Request::unsafe_arena_release_gameinfo() {
  // @@protoc_insertion_point(field_release:DS_Protobuf.NewDSGame_Request.gameinfo)
  
  ::DS_Protobuf::DSGameinfo* temp = _impl_.gameinfo_;
  _impl_.gameinfo_ = nullptr;
  return temp;
}
inline ::DS_Protobuf::DSGameinfo* NewDSGame_Request::_internal_mutable_gameinfo() {
  
  if (_impl_.gameinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::DS_Protobuf::DSGameinfo>(GetArenaForAllocation());
    _impl_.gameinfo_ = p;
  }
  return _impl_.gameinfo_;
}
inline ::DS_Protobuf::DSGameinfo* NewDSGame_Request::mutable_gameinfo() {
  ::DS_Protobuf::DSGameinfo* _msg = _internal_mutable_gameinfo();
  // @@protoc_insertion_point(field_mutable:DS_Protobuf.NewDSGame_Request.gameinfo)
  return _msg;
}
inline void NewDSGame_Request::set_allocated_gameinfo(::DS_Protobuf::DSGameinfo* gameinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.gameinfo_;
  }
  if (gameinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(gameinfo);
    if (message_arena != submessage_arena) {
      gameinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gameinfo, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.gameinfo_ = gameinfo;
  // @@protoc_insertion_point(field_set_allocated:DS_Protobuf.NewDSGame_Request.gameinfo)
}

// -------------------------------------------------------------------

// NewDSGame_Response

// int32 result = 1;
inline void NewDSGame_Response::clear_result() {
  _impl_.result_ = 0;
}
inline int32_t NewDSGame_Response::_internal_result() const {
  return _impl_.result_;
}
inline int32_t NewDSGame_Response::result() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.NewDSGame_Response.result)
  return _internal_result();
}
inline void NewDSGame_Response::_internal_set_result(int32_t value) {
  
  _impl_.result_ = value;
}
inline void NewDSGame_Response::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.NewDSGame_Response.result)
}

// int32 Port = 2;
inline void NewDSGame_Response::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t NewDSGame_Response::_internal_port() const {
  return _impl_.port_;
}
inline int32_t NewDSGame_Response::port() const {
  // @@protoc_insertion_point(field_get:DS_Protobuf.NewDSGame_Response.Port)
  return _internal_port();
}
inline void NewDSGame_Response::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void NewDSGame_Response::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:DS_Protobuf.NewDSGame_Response.Port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DS_Protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DS_5fProtocol_2eproto
