// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game_Protocol.proto

#include "Game_Protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Game_Protobuf {
PROTOBUF_CONSTEXPR PlayerAllinfo::PlayerAllinfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playersname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_.group_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerAllinfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerAllinfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerAllinfoDefaultTypeInternal() {}
  union {
    PlayerAllinfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerAllinfoDefaultTypeInternal _PlayerAllinfo_default_instance_;
PROTOBUF_CONSTEXPR Gameinfo::Gameinfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playersallinfo_)*/{}
  , /*decltype(_impl_.roomid_)*/0
  , /*decltype(_impl_.playersnum_)*/0
  , /*decltype(_impl_.playerslimit_)*/0
  , /*decltype(_impl_.mapid_)*/0
  , /*decltype(_impl_.hostid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameinfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameinfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameinfoDefaultTypeInternal() {}
  union {
    Gameinfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameinfoDefaultTypeInternal _Gameinfo_default_instance_;
PROTOBUF_CONSTEXPR NewGame_Request::NewGame_Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.gameinfo_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NewGame_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewGame_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewGame_RequestDefaultTypeInternal() {}
  union {
    NewGame_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewGame_RequestDefaultTypeInternal _NewGame_Request_default_instance_;
PROTOBUF_CONSTEXPR NewGame_Response::NewGame_Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ds_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NewGame_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewGame_ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewGame_ResponseDefaultTypeInternal() {}
  union {
    NewGame_Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewGame_ResponseDefaultTypeInternal _NewGame_Response_default_instance_;
}  // namespace Game_Protobuf
static ::_pb::Metadata file_level_metadata_Game_5fProtocol_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Game_5fProtocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Game_5fProtocol_2eproto = nullptr;

const uint32_t TableStruct_Game_5fProtocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::PlayerAllinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::PlayerAllinfo, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::PlayerAllinfo, _impl_.playersname_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::PlayerAllinfo, _impl_.token_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::PlayerAllinfo, _impl_.group_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _impl_.roomid_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _impl_.playersnum_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _impl_.playerslimit_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _impl_.mapid_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _impl_.hostid_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::Gameinfo, _impl_.playersallinfo_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::NewGame_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::NewGame_Request, _impl_.gameinfo_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::NewGame_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::NewGame_Response, _impl_.result_),
  PROTOBUF_FIELD_OFFSET(::Game_Protobuf::NewGame_Response, _impl_.ds_ip_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Game_Protobuf::PlayerAllinfo)},
  { 10, -1, -1, sizeof(::Game_Protobuf::Gameinfo)},
  { 22, -1, -1, sizeof(::Game_Protobuf::NewGame_Request)},
  { 29, -1, -1, sizeof(::Game_Protobuf::NewGame_Response)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Game_Protobuf::_PlayerAllinfo_default_instance_._instance,
  &::Game_Protobuf::_Gameinfo_default_instance_._instance,
  &::Game_Protobuf::_NewGame_Request_default_instance_._instance,
  &::Game_Protobuf::_NewGame_Response_default_instance_._instance,
};

const char descriptor_table_protodef_Game_5fProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023Game_Protocol.proto\022\rGame_Protobuf\"N\n\r"
  "PlayerAllinfo\022\n\n\002id\030\001 \001(\005\022\023\n\013playersname"
  "\030\002 \001(\t\022\r\n\005token\030\003 \001(\t\022\r\n\005group\030\004 \001(\005\"\231\001\n"
  "\010Gameinfo\022\016\n\006roomid\030\001 \001(\005\022\022\n\nplayersnum\030"
  "\002 \001(\005\022\024\n\014playerslimit\030\003 \001(\005\022\r\n\005mapid\030\004 \001"
  "(\005\022\016\n\006hostid\030\005 \001(\005\0224\n\016playersallinfo\030\006 \003"
  "(\0132\034.Game_Protobuf.PlayerAllinfo\"<\n\017NewG"
  "ame_Request\022)\n\010gameinfo\030\001 \001(\0132\027.Game_Pro"
  "tobuf.Gameinfo\"1\n\020NewGame_Response\022\016\n\006re"
  "sult\030\001 \001(\005\022\r\n\005DS_IP\030\002 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Game_5fProtocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Game_5fProtocol_2eproto = {
    false, false, 393, descriptor_table_protodef_Game_5fProtocol_2eproto,
    "Game_Protocol.proto",
    &descriptor_table_Game_5fProtocol_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_Game_5fProtocol_2eproto::offsets,
    file_level_metadata_Game_5fProtocol_2eproto, file_level_enum_descriptors_Game_5fProtocol_2eproto,
    file_level_service_descriptors_Game_5fProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Game_5fProtocol_2eproto_getter() {
  return &descriptor_table_Game_5fProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Game_5fProtocol_2eproto(&descriptor_table_Game_5fProtocol_2eproto);
namespace Game_Protobuf {

// ===================================================================

class PlayerAllinfo::_Internal {
 public:
};

PlayerAllinfo::PlayerAllinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Game_Protobuf.PlayerAllinfo)
}
PlayerAllinfo::PlayerAllinfo(const PlayerAllinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerAllinfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playersname_){}
    , decltype(_impl_.token_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.group_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.playersname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.playersname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_playersname().empty()) {
    _this->_impl_.playersname_.Set(from._internal_playersname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token().empty()) {
    _this->_impl_.token_.Set(from._internal_token(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.group_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.group_));
  // @@protoc_insertion_point(copy_constructor:Game_Protobuf.PlayerAllinfo)
}

inline void PlayerAllinfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playersname_){}
    , decltype(_impl_.token_){}
    , decltype(_impl_.id_){0}
    , decltype(_impl_.group_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.playersname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.playersname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerAllinfo::~PlayerAllinfo() {
  // @@protoc_insertion_point(destructor:Game_Protobuf.PlayerAllinfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerAllinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.playersname_.Destroy();
  _impl_.token_.Destroy();
}

void PlayerAllinfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerAllinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Game_Protobuf.PlayerAllinfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playersname_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.group_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.group_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerAllinfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string playersname = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_playersname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Game_Protobuf.PlayerAllinfo.playersname"));
        } else
          goto handle_unusual;
        continue;
      // string token = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Game_Protobuf.PlayerAllinfo.token"));
        } else
          goto handle_unusual;
        continue;
      // int32 group = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.group_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerAllinfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Game_Protobuf.PlayerAllinfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // string playersname = 2;
  if (!this->_internal_playersname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_playersname().data(), static_cast<int>(this->_internal_playersname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Game_Protobuf.PlayerAllinfo.playersname");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_playersname(), target);
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token().data(), static_cast<int>(this->_internal_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Game_Protobuf.PlayerAllinfo.token");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_token(), target);
  }

  // int32 group = 4;
  if (this->_internal_group() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_group(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Game_Protobuf.PlayerAllinfo)
  return target;
}

size_t PlayerAllinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Game_Protobuf.PlayerAllinfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string playersname = 2;
  if (!this->_internal_playersname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_playersname());
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // int32 group = 4;
  if (this->_internal_group() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_group());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerAllinfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerAllinfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerAllinfo::GetClassData() const { return &_class_data_; }


void PlayerAllinfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerAllinfo*>(&to_msg);
  auto& from = static_cast<const PlayerAllinfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Game_Protobuf.PlayerAllinfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_playersname().empty()) {
    _this->_internal_set_playersname(from._internal_playersname());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_group() != 0) {
    _this->_internal_set_group(from._internal_group());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerAllinfo::CopyFrom(const PlayerAllinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Game_Protobuf.PlayerAllinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerAllinfo::IsInitialized() const {
  return true;
}

void PlayerAllinfo::InternalSwap(PlayerAllinfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.playersname_, lhs_arena,
      &other->_impl_.playersname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.token_, lhs_arena,
      &other->_impl_.token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerAllinfo, _impl_.group_)
      + sizeof(PlayerAllinfo::_impl_.group_)
      - PROTOBUF_FIELD_OFFSET(PlayerAllinfo, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerAllinfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Game_5fProtocol_2eproto_getter, &descriptor_table_Game_5fProtocol_2eproto_once,
      file_level_metadata_Game_5fProtocol_2eproto[0]);
}

// ===================================================================

class Gameinfo::_Internal {
 public:
};

Gameinfo::Gameinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Game_Protobuf.Gameinfo)
}
Gameinfo::Gameinfo(const Gameinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Gameinfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playersallinfo_){from._impl_.playersallinfo_}
    , decltype(_impl_.roomid_){}
    , decltype(_impl_.playersnum_){}
    , decltype(_impl_.playerslimit_){}
    , decltype(_impl_.mapid_){}
    , decltype(_impl_.hostid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.roomid_, &from._impl_.roomid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.hostid_) -
    reinterpret_cast<char*>(&_impl_.roomid_)) + sizeof(_impl_.hostid_));
  // @@protoc_insertion_point(copy_constructor:Game_Protobuf.Gameinfo)
}

inline void Gameinfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playersallinfo_){arena}
    , decltype(_impl_.roomid_){0}
    , decltype(_impl_.playersnum_){0}
    , decltype(_impl_.playerslimit_){0}
    , decltype(_impl_.mapid_){0}
    , decltype(_impl_.hostid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Gameinfo::~Gameinfo() {
  // @@protoc_insertion_point(destructor:Game_Protobuf.Gameinfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Gameinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.playersallinfo_.~RepeatedPtrField();
}

void Gameinfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Gameinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Game_Protobuf.Gameinfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playersallinfo_.Clear();
  ::memset(&_impl_.roomid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.hostid_) -
      reinterpret_cast<char*>(&_impl_.roomid_)) + sizeof(_impl_.hostid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Gameinfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 roomid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.roomid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 playersnum = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.playersnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 playerslimit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.playerslimit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mapid = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.mapid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 hostid = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.hostid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .Game_Protobuf.PlayerAllinfo playersallinfo = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_playersallinfo(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Gameinfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Game_Protobuf.Gameinfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 roomid = 1;
  if (this->_internal_roomid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_roomid(), target);
  }

  // int32 playersnum = 2;
  if (this->_internal_playersnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_playersnum(), target);
  }

  // int32 playerslimit = 3;
  if (this->_internal_playerslimit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_playerslimit(), target);
  }

  // int32 mapid = 4;
  if (this->_internal_mapid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_mapid(), target);
  }

  // int32 hostid = 5;
  if (this->_internal_hostid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_hostid(), target);
  }

  // repeated .Game_Protobuf.PlayerAllinfo playersallinfo = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_playersallinfo_size()); i < n; i++) {
    const auto& repfield = this->_internal_playersallinfo(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Game_Protobuf.Gameinfo)
  return target;
}

size_t Gameinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Game_Protobuf.Gameinfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Game_Protobuf.PlayerAllinfo playersallinfo = 6;
  total_size += 1UL * this->_internal_playersallinfo_size();
  for (const auto& msg : this->_impl_.playersallinfo_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 roomid = 1;
  if (this->_internal_roomid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_roomid());
  }

  // int32 playersnum = 2;
  if (this->_internal_playersnum() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_playersnum());
  }

  // int32 playerslimit = 3;
  if (this->_internal_playerslimit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_playerslimit());
  }

  // int32 mapid = 4;
  if (this->_internal_mapid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mapid());
  }

  // int32 hostid = 5;
  if (this->_internal_hostid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hostid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Gameinfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Gameinfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Gameinfo::GetClassData() const { return &_class_data_; }


void Gameinfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Gameinfo*>(&to_msg);
  auto& from = static_cast<const Gameinfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Game_Protobuf.Gameinfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.playersallinfo_.MergeFrom(from._impl_.playersallinfo_);
  if (from._internal_roomid() != 0) {
    _this->_internal_set_roomid(from._internal_roomid());
  }
  if (from._internal_playersnum() != 0) {
    _this->_internal_set_playersnum(from._internal_playersnum());
  }
  if (from._internal_playerslimit() != 0) {
    _this->_internal_set_playerslimit(from._internal_playerslimit());
  }
  if (from._internal_mapid() != 0) {
    _this->_internal_set_mapid(from._internal_mapid());
  }
  if (from._internal_hostid() != 0) {
    _this->_internal_set_hostid(from._internal_hostid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Gameinfo::CopyFrom(const Gameinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Game_Protobuf.Gameinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Gameinfo::IsInitialized() const {
  return true;
}

void Gameinfo::InternalSwap(Gameinfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.playersallinfo_.InternalSwap(&other->_impl_.playersallinfo_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Gameinfo, _impl_.hostid_)
      + sizeof(Gameinfo::_impl_.hostid_)
      - PROTOBUF_FIELD_OFFSET(Gameinfo, _impl_.roomid_)>(
          reinterpret_cast<char*>(&_impl_.roomid_),
          reinterpret_cast<char*>(&other->_impl_.roomid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Gameinfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Game_5fProtocol_2eproto_getter, &descriptor_table_Game_5fProtocol_2eproto_once,
      file_level_metadata_Game_5fProtocol_2eproto[1]);
}

// ===================================================================

class NewGame_Request::_Internal {
 public:
  static const ::Game_Protobuf::Gameinfo& gameinfo(const NewGame_Request* msg);
};

const ::Game_Protobuf::Gameinfo&
NewGame_Request::_Internal::gameinfo(const NewGame_Request* msg) {
  return *msg->_impl_.gameinfo_;
}
NewGame_Request::NewGame_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Game_Protobuf.NewGame_Request)
}
NewGame_Request::NewGame_Request(const NewGame_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  NewGame_Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.gameinfo_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_gameinfo()) {
    _this->_impl_.gameinfo_ = new ::Game_Protobuf::Gameinfo(*from._impl_.gameinfo_);
  }
  // @@protoc_insertion_point(copy_constructor:Game_Protobuf.NewGame_Request)
}

inline void NewGame_Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.gameinfo_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

NewGame_Request::~NewGame_Request() {
  // @@protoc_insertion_point(destructor:Game_Protobuf.NewGame_Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NewGame_Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.gameinfo_;
}

void NewGame_Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NewGame_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:Game_Protobuf.NewGame_Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.gameinfo_ != nullptr) {
    delete _impl_.gameinfo_;
  }
  _impl_.gameinfo_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NewGame_Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Game_Protobuf.Gameinfo gameinfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_gameinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NewGame_Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Game_Protobuf.NewGame_Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Game_Protobuf.Gameinfo gameinfo = 1;
  if (this->_internal_has_gameinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::gameinfo(this),
        _Internal::gameinfo(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Game_Protobuf.NewGame_Request)
  return target;
}

size_t NewGame_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Game_Protobuf.NewGame_Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Game_Protobuf.Gameinfo gameinfo = 1;
  if (this->_internal_has_gameinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.gameinfo_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NewGame_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NewGame_Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NewGame_Request::GetClassData() const { return &_class_data_; }


void NewGame_Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NewGame_Request*>(&to_msg);
  auto& from = static_cast<const NewGame_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Game_Protobuf.NewGame_Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_gameinfo()) {
    _this->_internal_mutable_gameinfo()->::Game_Protobuf::Gameinfo::MergeFrom(
        from._internal_gameinfo());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NewGame_Request::CopyFrom(const NewGame_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Game_Protobuf.NewGame_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewGame_Request::IsInitialized() const {
  return true;
}

void NewGame_Request::InternalSwap(NewGame_Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.gameinfo_, other->_impl_.gameinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NewGame_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Game_5fProtocol_2eproto_getter, &descriptor_table_Game_5fProtocol_2eproto_once,
      file_level_metadata_Game_5fProtocol_2eproto[2]);
}

// ===================================================================

class NewGame_Response::_Internal {
 public:
};

NewGame_Response::NewGame_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Game_Protobuf.NewGame_Response)
}
NewGame_Response::NewGame_Response(const NewGame_Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  NewGame_Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ds_ip_){}
    , decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ds_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ds_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ds_ip().empty()) {
    _this->_impl_.ds_ip_.Set(from._internal_ds_ip(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:Game_Protobuf.NewGame_Response)
}

inline void NewGame_Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ds_ip_){}
    , decltype(_impl_.result_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ds_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ds_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

NewGame_Response::~NewGame_Response() {
  // @@protoc_insertion_point(destructor:Game_Protobuf.NewGame_Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NewGame_Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ds_ip_.Destroy();
}

void NewGame_Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NewGame_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:Game_Protobuf.NewGame_Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ds_ip_.ClearToEmpty();
  _impl_.result_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NewGame_Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string DS_IP = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_ds_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Game_Protobuf.NewGame_Response.DS_IP"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NewGame_Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Game_Protobuf.NewGame_Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
  }

  // string DS_IP = 2;
  if (!this->_internal_ds_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ds_ip().data(), static_cast<int>(this->_internal_ds_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Game_Protobuf.NewGame_Response.DS_IP");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_ds_ip(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Game_Protobuf.NewGame_Response)
  return target;
}

size_t NewGame_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Game_Protobuf.NewGame_Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string DS_IP = 2;
  if (!this->_internal_ds_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ds_ip());
  }

  // int32 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NewGame_Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NewGame_Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NewGame_Response::GetClassData() const { return &_class_data_; }


void NewGame_Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NewGame_Response*>(&to_msg);
  auto& from = static_cast<const NewGame_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Game_Protobuf.NewGame_Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ds_ip().empty()) {
    _this->_internal_set_ds_ip(from._internal_ds_ip());
  }
  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NewGame_Response::CopyFrom(const NewGame_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Game_Protobuf.NewGame_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewGame_Response::IsInitialized() const {
  return true;
}

void NewGame_Response::InternalSwap(NewGame_Response* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ds_ip_, lhs_arena,
      &other->_impl_.ds_ip_, rhs_arena
  );
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NewGame_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Game_5fProtocol_2eproto_getter, &descriptor_table_Game_5fProtocol_2eproto_once,
      file_level_metadata_Game_5fProtocol_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Game_Protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Game_Protobuf::PlayerAllinfo*
Arena::CreateMaybeMessage< ::Game_Protobuf::PlayerAllinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Game_Protobuf::PlayerAllinfo >(arena);
}
template<> PROTOBUF_NOINLINE ::Game_Protobuf::Gameinfo*
Arena::CreateMaybeMessage< ::Game_Protobuf::Gameinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Game_Protobuf::Gameinfo >(arena);
}
template<> PROTOBUF_NOINLINE ::Game_Protobuf::NewGame_Request*
Arena::CreateMaybeMessage< ::Game_Protobuf::NewGame_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Game_Protobuf::NewGame_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::Game_Protobuf::NewGame_Response*
Arena::CreateMaybeMessage< ::Game_Protobuf::NewGame_Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Game_Protobuf::NewGame_Response >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
